import {
  chakraui,
  depelopment,
  deprecated,
  finished,
  javascript,
  nextjs,
  reactjs,
  tailwindcss,
  TProject,
  typescript,
  vuejs,
} from './tech';

export const kloningan: TProject[] = [
  {
    id: 1,
    title: 'Main Website Kloningan',
    description: 'Start by Imitating the Existing One, Then Create a Better One!',
    href: 'https://www.kloningan.com',
    image: require('@/images/projects/kloningan-com.jpg').default,
    github: 'https://www.github.com/kloningan/kloningan.com',
    tech: [typescript, nextjs, tailwindcss],
    status: [depelopment],
  },
  {
    id: 2,
    title: 'Pikobar UI Clone',
    description: 'Pusat Informasi & Koordinasi Covid-19 Jawa Barat!',
    href: '#',
    github: '#',
    tech: [typescript, nextjs, tailwindcss],
    status: [depelopment],
  },
];

export const random: TProject[] = [
  {
    id: 1,
    title: 'Movies and Games Rating',
    description: 'Website That Show Ratings Popular Movies and Games!',
    href: 'https://fahmi-final-project.netlify.app',
    image: require('@/images/projects/movies-and-games-rating.jpg').default,
    github: 'https://github.com/fahmiidris-labs/React-JS-JCC-2021/tree/main/Final-Project',
    tech: [javascript, reactjs, chakraui],
    status: [finished, deprecated],
  },
  {
    id: 2,
    title: 'Bansos Ku',
    description: 'Only Form Validation Level Frontend Using Formik!',
    href: 'https://bansosku.netlify.app',
    image: require('@/images/projects/bansosku.jpg').default,
    github: 'https://www.github.com/fahmiidris-labs/bansosku',
    tech: [typescript, nextjs, tailwindcss],
    status: [finished, deprecated],
  },
  {
    id: 3,
    title: 'Clover Web App',
    description: 'Embrance New Ways to Farm!',
    href: 'https://clover-app.vercel.app',
    image: require('@/images/projects/clover.jpg').default,
    tech: [javascript, nextjs, tailwindcss],
    status: [finished, deprecated],
  },
  {
    id: 4,
    title: 'Buku Angkatan JCC Offline 2021',
    description: 'Tinggal di Desa, Rezeki Kota, Skill Mendunia!',
    href: 'https://jcc-offline-member.netlify.app',
    image: require('@/images/projects/class-book.jpg').default,
    github: 'https://github.com/fahmiidris-labs/buku-angkatan-jcc-2021',
    tech: [typescript, nextjs, tailwindcss],
    status: [finished, deprecated],
  },
  {
    id: 5,
    title: 'Todo List Management',
    description: 'Todo List Management for Manage Your Task!',
    href: 'https://todo.fahmiidris.dev',
    github: 'https://www.github.com/fahmiidris-labs/todo.fahmiidris.dev',
    tech: [typescript, vuejs, tailwindcss],
    status: [depelopment],
  },
  {
    id: 6,
    title: 'Starter Template Documentation',
    description: 'Documentation for Starter Template.',
    href: 'https://starter-template.fahmiidris.dev',
    github: 'https://github.com/fahmiidris-labs/starter-template.fahmiidris.dev',
    image: require('@/images/projects/starter-template.jpg').default,
    tech: [typescript, nextjs, tailwindcss],
    status: [depelopment],
  },
  {
    id: 7,
    title: 'Personal Portfolio Website',
    description:
      'Fahmi Idris Personal Portfolio Website, Blog, Project Showcase, and My Experience History.',
    href: 'https://www.fahmiidris.dev',
    image: require('@/images/projects/fahmiidris-dev.jpg').default,
    github: 'https://github.com/fahmiidris-labs/fahmiidris.dev',
    tech: [typescript, nextjs, tailwindcss],
    status: [finished, depelopment],
  },
  {
    id: 8,
    title: 'My Graduation Presentation',
    description: 'Graduation Presentation for My Graduation in eFishery.',
    href: 'https://graduation-efishery.fahmiidris.dev',
    image: require('@/images/projects/graduation-efishery.jpg').default,
    github: 'https://github.com/fahmiidris-labs/graduation-efishery.fahmiidris.dev',
    tech: [javascript, nextjs, tailwindcss],
    status: [depelopment],
  },
  {
    id: 9,
    title: 'Hujan Gak? - Weather Forecast',
    description: 'Weather Forecast for Indonesia!',
    href: 'https://hujan-gak.netlify.app',
    image: require('@/images/projects/hujan-gak.jpg').default,
    github: 'https://github.com/fahmiidris-labs/hujan-gak',
    tech: [javascript, reactjs, tailwindcss],
    status: [finished, depelopment],
  },
  {
    id: 10,
    title: 'Open Graph Generator',
    description: 'Open Graph Generator for Personal Use!',
    href: 'https://og.fahmiidris.dev',
    github: 'https://github.com/fahmiidris-labs/og.fahmiidris.dev',
    tech: [typescript],
    status: [depelopment],
  },
];
