env:
    browser: true
    node: true

plugins:
    - '@typescript-eslint'

extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'next/core-web-vitals'
    - 'prettier'

parser: '@typescript-eslint/parser'

rules:
    no-console: 'warn'

globals:
    JSX: true
    React: true
